### ISSUE TITLE
Cannot install requirements

### ISSUE THREAD

**Issue by LukeMarlin** [MaevaBrunelles/vegalt#1]
Trying to install requirements fails because it lists `os`, which is standard and therefore not to be collected from pip:

    23:12 $ pip install -r requirements.txt 
    Collecting os (from -r requirements.txt (line 1))
      Could not find a version that satisfies the requirement os (from -r requirements.txt (line 1)) (from versions: )
    No matching distribution found for os (from -r requirements.txt (line 1))

**Comment by MaevaBrunelles** [comment]
Fixed issue with commit d906cc1
